ALTER TABLE "WorldEvent"
ADD COLUMN IF NOT EXISTS "impactLevel" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "WorldEvent"
ADD COLUMN IF NOT EXISTS "payload" JSONB;

ALTER TYPE "WorldEventType" ADD VALUE IF NOT EXISTS 'WORLD_CREATED';
ALTER TYPE "WorldEventType" ADD VALUE IF NOT EXISTS 'CAMPAIGN_CREATED';
ALTER TYPE "WorldEventType" ADD VALUE IF NOT EXISTS 'CHARACTER_CREATED';
ALTER TYPE "WorldEventType" ADD VALUE IF NOT EXISTS 'COMBAT_STARTED';
ALTER TYPE "WorldEventType" ADD VALUE IF NOT EXISTS 'COMBAT_ENDED';
